# Generated by Django 3.2 on 2023-03-29 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion_Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verificacion', models.BooleanField()),
                ('entrega', models.BooleanField()),
                ('devolucion', models.BooleanField()),
                ('id_senape', models.IntegerField(default=0, help_text='Introduzca el ID. SENAPE')),
                ('cod_vsiaf', models.IntegerField(default=0, help_text='Introduzca el COD. VSIAF')),
                ('fecha', models.DateTimeField()),
                ('persona_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.persona')),
                ('unidad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.unidad')),
                ('vehiculo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.vehiculo')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
