# Generated by Django 3.2 on 2023-06-26 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mecanico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci_mecanico', models.CharField(max_length=10, unique=True)),
                ('nombres_mecanico', models.CharField(max_length=50)),
                ('ap_paterno_mecanico', models.CharField(max_length=30)),
                ('ap_materno_mecanico', models.CharField(blank=True, default=' ', max_length=30, null=True)),
                ('cargo', models.CharField(max_length=20)),
                ('telefono', models.PositiveIntegerField(unique=True)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Cambio_Aceite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km_actual', models.PositiveBigIntegerField(default=0)),
                ('proximo_cambio', models.PositiveBigIntegerField(default=5000)),
                ('cambio_filtros', models.BooleanField(default=False)),
                ('aceite', models.BooleanField(default=False)),
                ('caja', models.BooleanField(default=False)),
                ('corona', models.BooleanField(default=False)),
                ('engrase', models.BooleanField(default=False)),
                ('fecha_hora_entrada', models.DateField()),
                ('maestranza', models.CharField(default='Maestranza', max_length=100)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('aprobado', models.BooleanField(default=False)),
                ('chofer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.chofer')),
                ('mecanico_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignacion.mecanico')),
                ('unidad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.unidad')),
                ('vehiculo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Asignacion_Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verificacion_entrega', models.BooleanField(default=True)),
                ('entrega', models.BooleanField(default=True)),
                ('verificacion_devolucion', models.BooleanField(default=False)),
                ('devolucion', models.BooleanField(default=False)),
                ('fecha', models.DateField()),
                ('fecha_devolucion', models.DateField(blank=True, null=True)),
                ('id_senape', models.PositiveIntegerField(unique=True)),
                ('cod_vsiaf', models.PositiveIntegerField(unique=True)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('chofer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.chofer')),
                ('unidad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.unidad')),
                ('vehiculo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.vehiculo')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
