# Generated by Django 3.2 on 2023-05-07 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion_vehiculo',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
