# Generated by Django 3.2 on 2023-05-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion', '0002_asignacion_vehiculo_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion_vehiculo',
            name='fecha',
            field=models.DateField(),
        ),
    ]
