# Generated by Django 3.2 on 2023-05-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion', '0004_asignacion_vehiculo_fecha_devolucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion_vehiculo',
            name='devolucion',
            field=models.BooleanField(default=False),
        ),
    ]
