# Generated by Django 3.2 on 2023-05-17 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion', '0005_alter_asignacion_vehiculo_devolucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion_vehiculo',
            name='cod_vsiaf',
            field=models.PositiveIntegerField(help_text='Introduzca el COD. VSIAF'),
        ),
        migrations.AlterField(
            model_name='asignacion_vehiculo',
            name='entrega',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='asignacion_vehiculo',
            name='id_senape',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='asignacion_vehiculo',
            name='verificacion',
            field=models.BooleanField(default=True),
        ),
    ]
