# Generated by Django 3.2 on 2023-05-26 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion', '0007_alter_asignacion_vehiculo_cod_vsiaf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignacion_vehiculo',
            old_name='persona_id',
            new_name='chofer_id',
        ),
    ]
