# Generated by Django 3.2 on 2023-05-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion', '0009_cambio_aceite'),
    ]

    operations = [
        migrations.AddField(
            model_name='cambio_aceite',
            name='fecha_hora_entrada',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cambio_aceite',
            name='lugar_revision',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cambio_aceite',
            name='hora_salida',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='cambio_aceite',
            name='maestranza',
            field=models.BooleanField(default=False),
        ),
    ]
