# Generated by Django 3.2 on 2023-05-29 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion', '0010_auto_20230529_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cambio_aceite',
            name='fecha_hora_entrada',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cambio_aceite',
            name='hora_salida',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cambio_aceite',
            name='lugar_revision',
            field=models.CharField(max_length=200),
        ),
    ]
