# Generated by Django 3.2 on 2023-05-29 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion', '0014_cambio_aceite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cambio_aceite',
            name='chofer_id',
        ),
        migrations.RemoveField(
            model_name='cambio_aceite',
            name='unidad_id',
        ),
        migrations.RemoveField(
            model_name='cambio_aceite',
            name='vehiculo_id',
        ),
    ]
