# Generated by Django 3.2 on 2023-05-29 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0037_delete_cliente'),
        ('asignacion', '0016_auto_20230529_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cambio_aceite',
            name='chofer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.chofer'),
        ),
        migrations.AlterField(
            model_name='cambio_aceite',
            name='unidad_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.unidad'),
        ),
        migrations.AlterField(
            model_name='cambio_aceite',
            name='vehiculo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.vehiculo'),
        ),
    ]
