# Generated by Django 3.2 on 2023-05-29 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion', '0017_auto_20230529_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cambio_aceite',
            name='hora_salida',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
