# Generated by Django 3.2 on 2023-05-29 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion', '0018_alter_cambio_aceite_hora_salida'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cambio_Aceite',
        ),
    ]
