# Generated by Django 3.2 on 2023-05-29 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0037_delete_cliente'),
        ('asignacion', '0019_delete_cambio_aceite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cambio_Aceite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mecanico', models.CharField(max_length=20)),
                ('ap_paterno_mecanico', models.CharField(max_length=20)),
                ('ap_materno_mecanico', models.CharField(blank=True, default=' ', max_length=20, null=True)),
                ('km_actual', models.PositiveBigIntegerField(default=0)),
                ('proximo_cambio', models.PositiveBigIntegerField(default=5000)),
                ('cambio_filtros', models.BooleanField(default=False)),
                ('aceite', models.BooleanField(default=False)),
                ('caja', models.CharField(max_length=100)),
                ('corona', models.CharField(max_length=100)),
                ('engrase', models.BooleanField(default=False)),
                ('fecha_hora_entrada', models.DateField()),
                ('lugar_revision', models.CharField(max_length=200)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('maestranza', models.BooleanField(default=False)),
                ('autorizacion', models.BooleanField(choices=[(True, 'Pendiente'), (False, 'Aprobado')], default=False)),
                ('chofer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.chofer')),
                ('unidad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.unidad')),
                ('vehiculo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.vehiculo')),
            ],
        ),
    ]
