# Generated by Django 3.2 on 2023-06-02 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion', '0021_auto_20230530_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='mecanico',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
