# Generated by Django 3.2 on 2023-06-02 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion', '0022_mecanico_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion_vehiculo',
            name='cod_vsiaf',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='asignacion_vehiculo',
            name='id_senape',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
