# Generated by Django 3.2 on 2023-06-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion', '0023_auto_20230601_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cambio_aceite',
            name='maestranza',
            field=models.CharField(default='Maestranza', max_length=100),
        ),
    ]
