# Generated by Django 3.2 on 2023-06-26 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(max_length=10, unique=True)),
                ('nombres', models.CharField(max_length=20)),
                ('apellido_paterno', models.CharField(max_length=20)),
                ('apellido_materno', models.CharField(blank=True, default=' ', max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, default=' ', max_length=50, null=True)),
                ('telefono', models.PositiveIntegerField(unique=True)),
                ('categoria_lic', models.CharField(choices=[('', '----Seleccione----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('M', 'M'), ('T', 'T'), ('A y M', 'A y M'), ('B y M', 'B y M'), ('C y M', 'C y M'), ('T y M', 'T y M'), ('AMT', 'AMT'), ('BMT', 'BMT'), ('CMT', 'CMT')], default='', help_text='Seleccione una categoría de licencia', max_length=5)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'ordering': ['apellido_paterno', 'apellido_materno', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_secretaria', models.CharField(max_length=200, unique=True)),
                ('direccion', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase_vehiculo', models.CharField(choices=[('', '----Seleccione----'), ('MOTOCICLETA', 'MOTOCICLETA'), ('CAMIONETA', 'CAMIONETA'), ('VAGONETA', 'VAGONETA'), ('CISTERNA', 'CISTERNA'), ('CAMIÓN FRIGORÍFICO', 'CAMIÓN FRIGORÍFICO'), ('MAQUINARIA PESADA', 'MAQUINARIA PESADA')], help_text='Seleccione la clase de vehículo', max_length=18)),
                ('marca', models.CharField(max_length=15)),
                ('tipo_vehiculo', models.CharField(max_length=15)),
                ('procedencia', models.CharField(max_length=30)),
                ('modelo', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=10)),
                ('placa', models.CharField(max_length=15, unique=True)),
                ('cilindrada', models.PositiveIntegerField()),
                ('numero_motor', models.CharField(max_length=10)),
                ('numero_chasis', models.CharField(max_length=10)),
                ('estado_vehiculo', models.CharField(choices=[('', '----Seleccione----'), ('BUENO', 'BUENO'), ('REGULAR', 'REGULAR'), ('MALO', 'MALO')], default='', help_text='Seleccione el estado del vehículo', max_length=7)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'ordering': ['clase_vehiculo', 'marca', 'tipo_vehiculo'],
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_unidad', models.CharField(max_length=200, unique=True)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('secretaria_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.secretaria')),
            ],
        ),
    ]
