# Generated by Django 3.2 on 2023-03-29 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(help_text='Introduzca el numero de C.I.', max_length=10, unique=True)),
                ('nombres', models.CharField(help_text='Introduzca los nombres', max_length=20)),
                ('apellido_paterno', models.CharField(help_text='Introduzca el apellido paterno', max_length=20)),
                ('apellido_materno', models.CharField(help_text='Introduzca el apellido materno', max_length=20)),
                ('direccion', models.CharField(blank=True, help_text='Introduzca la direccion', max_length=50, null=True)),
                ('telefono', models.CharField(help_text='Introduzca el numero de telefono', max_length=10)),
            ],
            options={
                'ordering': ['apellido_paterno', 'apellido_materno', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_secretaria', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase_vehiculo', models.CharField(help_text='Introduzca la clase de vehiculo', max_length=30)),
                ('marca', models.CharField(help_text='Introduzca la marca del vehiculo', max_length=15)),
                ('tipo_vehiculo', models.CharField(help_text='Introduzca el tipo de vehiculo', max_length=15)),
                ('procedencia', models.CharField(help_text='Introduzca la procedencia del vehiculo', max_length=30)),
                ('modelo', models.CharField(help_text='Introduzca el modelo de vehiculo', max_length=30)),
                ('color', models.CharField(help_text='Introduzca el color del vehiculo', max_length=10)),
                ('placa', models.CharField(help_text='Introduzca la placa del vehiculo', max_length=15)),
                ('cilindrada', models.CharField(help_text='Introduzca la cilindrada del vehiculo', max_length=20)),
                ('numero_motor', models.IntegerField(default=0, help_text='Introduzca el numero de motor')),
                ('numero_chasis', models.IntegerField(default=0, help_text='Introduzca el numero de chasis')),
                ('estado_vehiculo', models.CharField(help_text='Introduzca el estado del vehiculo', max_length=10)),
                ('observaciones', models.CharField(help_text='Introduzca las observaciones del vehiculo', max_length=250)),
            ],
            options={
                'ordering': ['clase_vehiculo', 'marca', 'tipo_vehiculo'],
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_unidad', models.CharField(max_length=100)),
                ('secretaria_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.secretaria')),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaLic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_lic', models.CharField(max_length=30)),
                ('persona_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.persona')),
            ],
        ),
    ]
