# Generated by Django 3.2 on 2023-07-01 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='color',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='numero_chasis',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='numero_motor',
            field=models.CharField(max_length=20),
        ),
    ]
