# Generated by Django 3.2 on 2023-05-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
