# Generated by Django 3.2 on 2023-05-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_unidad_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='categoria_lic',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('M', 'M'), ('T', 'T'), ('A y M', 'A y M'), ('B y M', 'B y M'), ('C y M', 'C y M'), ('T y M', 'T y M'), ('AMT', 'AMT'), ('BMT', 'BMT'), ('CMT', 'CMT')], default='', max_length=5),
        ),
    ]
