# Generated by Django 3.2 on 2023-05-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_persona_categoria_lic'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.DeleteModel(
            name='CategoriaLic',
        ),
    ]
