# Generated by Django 3.2 on 2023-05-09 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_auto_20230509_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaLic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_lic', models.CharField(max_length=30)),
                ('persona_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.persona')),
            ],
        ),
    ]
