# Generated by Django 3.2 on 2023-05-09 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_categorialic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoriaLic',
        ),
    ]
