# Generated by Django 3.2 on 2023-05-09 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0009_auto_20230509_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretaria',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
