# Generated by Django 3.2 on 2023-05-09 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0012_alter_chofer_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chofer',
            name='direccion',
            field=models.CharField(blank=True, help_text='Introduzca la dirección', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='telefono',
            field=models.PositiveIntegerField(default=0, help_text='Introduzca el número de teléfono'),
        ),
    ]
