# Generated by Django 3.2 on 2023-05-09 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0013_auto_20230509_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chofer',
            name='telefono',
            field=models.PositiveIntegerField(help_text='Introduzca el número de teléfono'),
        ),
    ]
