# Generated by Django 3.2 on 2023-05-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0016_alter_chofer_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chofer',
            name='apellido_materno',
            field=models.CharField(blank=True, help_text='Introduzca el apellido materno', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='telefono',
            field=models.PositiveIntegerField(help_text='Introduzca el número de teléfono', unique=True),
        ),
        migrations.AlterField(
            model_name='secretaria',
            name='direccion',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='secretaria',
            name='nombre_secretaria',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='nombre_unidad',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='cilindrada',
            field=models.PositiveIntegerField(help_text='Introduzca la cilindrada del vehiculo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='estado_vehiculo',
            field=models.CharField(choices=[('BUENO', 1), ('REGULAR', 2), ('MALO', 3)], default='', help_text='Seleccione el estado del vehículo', max_length=7),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='numero_chasis',
            field=models.CharField(help_text='Introduzca el numero de chasis', max_length=10),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='numero_motor',
            field=models.CharField(help_text='Introduzca el numero de motor', max_length=10),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='observaciones',
            field=models.TextField(help_text='Introduzca las observaciones del vehiculo', max_length=250),
        ),
    ]
