# Generated by Django 3.2 on 2023-05-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0020_auto_20230515_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretaria',
            name='direccion',
            field=models.CharField(max_length=40),
        ),
    ]
