# Generated by Django 3.2 on 2023-05-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0021_alter_secretaria_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='estado_vehiculo',
            field=models.CharField(choices=[('BUENO', 'BUENO'), ('REGULAR', 'REGULAR'), ('MALO', 'MALO')], default='', help_text='Seleccione el estado del vehículo', max_length=7),
        ),
    ]
