# Generated by Django 3.2 on 2023-05-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0022_alter_vehiculo_estado_vehiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretaria',
            name='direccion',
            field=models.CharField(max_length=50),
        ),
    ]
