# Generated by Django 3.2 on 2023-05-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0025_alter_vehiculo_cilindrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='observaciones',
            field=models.TextField(help_text='Introduzca las observaciones del vehiculo'),
        ),
    ]
