# Generated by Django 3.2 on 2023-05-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0028_alter_chofer_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chofer',
            name='telefono',
            field=models.PositiveIntegerField(help_text='Introduzca el número de teléfono', unique=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='cilindrada',
            field=models.PositiveIntegerField(help_text='Introduzca la cilindrada del vehiculo'),
        ),
    ]
