# Generated by Django 3.2 on 2023-05-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0029_auto_20230515_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
