# Generated by Django 3.2 on 2023-05-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0030_vehiculo_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretaria',
            name='nombre_secretaria',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='nombre_unidad',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='cilindrada',
            field=models.PositiveIntegerField(help_text='Introduzca la cilindrada del vehículo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='clase_vehiculo',
            field=models.CharField(help_text='Introduzca la clase de vehículo', max_length=30),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='color',
            field=models.CharField(help_text='Introduzca el color del vehículo', max_length=10),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(help_text='Introduzca la marca del vehículo', max_length=15),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.CharField(help_text='Introduzca el modelo de vehículo', max_length=4),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='numero_motor',
            field=models.CharField(help_text='Introduzca el número de motor', max_length=10),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='observaciones',
            field=models.TextField(help_text='Introduzca las observaciones del vehículo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(help_text='Introduzca la placa del vehículo', max_length=15),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='procedencia',
            field=models.CharField(help_text='Introduzca la procedencia del vehículo', max_length=30),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo_vehiculo',
            field=models.CharField(help_text='Introduzca el tipo de vehículo', max_length=15),
        ),
    ]
