# Generated by Django 3.2 on 2023-05-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0031_auto_20230515_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chofer',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='apellido_paterno',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='ci',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='direccion',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='nombres',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='telefono',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
