# Generated by Django 3.2 on 2023-05-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0032_auto_20230515_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chofer',
            name='apellido_materno',
            field=models.CharField(blank=True, default=' ', max_length=20, null=True),
        ),
    ]
