# Generated by Django 3.2 on 2023-05-15 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0033_alter_chofer_apellido_materno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='cilindrada',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='clase_vehiculo',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='color',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='numero_chasis',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='numero_motor',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='observaciones',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='procedencia',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo_vehiculo',
            field=models.CharField(max_length=15),
        ),
    ]
