# Generated by Django 3.2 on 2023-05-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0034_auto_20230515_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
