# Generated by Django 3.2 on 2023-05-26 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0035_alter_vehiculo_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.PositiveIntegerField(),
        ),
    ]
