# Generated by Django 3.2 on 2023-05-29 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0036_alter_vehiculo_modelo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
