# Generated by Django 3.2 on 2023-05-30 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0037_delete_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretaria',
            name='nombre_secretaria',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='nombre_unidad',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
