# Generated by Django 3.2 on 2023-06-17 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0039_alter_vehiculo_clase_vehiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='clase_vehiculo',
            field=models.CharField(choices=[('', '----Seleccione----'), ('1', 'MOTOCICLETA'), ('2', 'CAMIONETA'), ('3', 'VAGONETA'), ('4', 'CISTERNA'), ('5', 'CAMIÓN FRIGORÍFICO'), ('6', 'MAQUINARIA PESADA')], help_text='Seleccione la clase de vehículo', max_length=18),
        ),
    ]
