# Generated by Django 3.2 on 2023-06-17 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0040_alter_vehiculo_clase_vehiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='estado_vehiculo',
            field=models.CharField(choices=[('', '----Seleccione----'), ('BUENO', 'BUENO'), ('REGULAR', 'REGULAR'), ('MALO', 'MALO')], default='', help_text='Seleccione el estado del vehículo', max_length=7),
        ),
    ]
