# Generated by Django 3.2 on 2023-06-17 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0041_alter_vehiculo_estado_vehiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='clase_vehiculo',
            field=models.CharField(choices=[('', '----Seleccione----'), ('MOTOCICLETA', 'MOTOCICLETA'), ('CAMIONETA', 'CAMIONETA'), ('VAGONETA', 'VAGONETA'), ('CISTERNA', 'CISTERNA'), ('CAMIÓN FRIGORÍFICO', 'CAMIÓN FRIGORÍFICO'), ('MAQUINARIA PESADA', 'MAQUINARIA PESADA')], help_text='Seleccione la clase de vehículo', max_length=18),
        ),
    ]
