# Generated by Django 3.2 on 2023-06-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0043_alter_chofer_categoria_lic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='procedencia',
            field=models.CharField(default='Maestranza', max_length=30),
        ),
    ]
