# Generated by Django 3.2 on 2023-06-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0044_alter_vehiculo_procedencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='procedencia',
            field=models.CharField(max_length=30),
        ),
    ]
